### PR TITLE
Change property `dimiss` to `dismiss`

### PR DESCRIPTION
**Pull request by rars**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

I think `dimiss` is likely a typo and it is more natural to call this property `dismiss`.

Issue Number: N/A

## What is the new behavior?
Property name is renamed to `dismiss`.

## Does this PR introduce a breaking change?

```
[ x] Yes
[ ] No
```

## Other information
BREAKING CHANGE: property `dimiss` is renamed to `dismiss` on help component and may cause compilation or runtime errors in clients that depend on the old name.

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Thanks. The breaking change should be in the commit message based on https://github.com/ngneat/hotkeys/blob/master/CONTRIBUTING.md#-commit-message-guidelines

**Comment by rars** [comment]
> Thanks. The breaking change should be in the commit message based on https://github.com/ngneat/hotkeys/blob/master/CONTRIBUTING.md#-commit-message-guidelines

Updated the commit message and the link to the sample commits in `CONTRIBUTING.md`.

**Comment by rars** [comment]
@NetanelBasal is there anything else that's needed for this?

**Comment by NetanelBasal** [comment]
@rars ci failed

**Comment by rars** [comment]
> @rars ci failed

Ok, think I've pushed a fix for that. Please try again.

**Pull request merged**
