### PR TITLE
Adding Sequence Hotkeys

### PR DESCRIPTION
**Pull request by jherman**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

This provides simple support for sequence hotkeys. See https://github.com/ngneat/hotkeys/issues/44 for more detail.

Issue Number: #44 

## What is the new behavior?

You can now specify a sequence of keys as a hotkey

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Please add specs first

**Comment by jherman** [comment]
First time committing to ngneat. I followed the templated document requests from the pull request. I also tried to follow and stay inline with the current documentation provided in the readme.md.

Can you point me to an example of the specs you are requesting? I want to make sure I meet your expectations to avoid as much back and forth commits. Thanks!

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/hotkeys/tree/master/projects/ngneat/hotkeys/src/lib/tests

**Comment by jherman** [comment]
Perfect. Thanks - I'll work on that shortly.

**Comment by jherman** [comment]
@NetanelBasal Updated specs to include sequence hotkeys.

**Comment by NetanelBasal** [comment]
@flatstadt can you check it, please?

**Comment by jherman** [comment]
Hi, just touching base. Any progress on this?

**Comment by NetanelBasal** [comment]
I'm waiting for the maintainer. If he doesn't respond soon, I'll check it.

**Comment by jherman** [comment]
@NetanelBasal Any news from the maintainer?

**Comment by jherman** [comment]
@NetanelBasal Thanks for merging! Is there anything I need to do to trigger npmjs.com to update their version? What is the typical protocol there?

**Comment by NetanelBasal** [comment]
done

**Pull request merged**
