### PR TITLE
Upgrade to Angular 16

### PR DESCRIPTION
**Pull request by gethari**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ x ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ x ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the new behavior?

- Upgraded lib to support Angular 16
- Upgraded all dependencies to latest stable version

## Does this PR introduce a breaking change?

```
[  ] Yes
[ x ] No
```

### CODE REVIEW

**Comment by gethari** [comment]
@NetanelBasal I also need the lib without `@angular/material` #82  dependency, any thoughts about how to go about it ? Should I directly remove it from dependencies ?

**Comment by gethari** [comment]
@NetanelBasal would appreciate any inputs here, please

**Comment by NetanelBasal** [comment]
Sure

**Comment by gethari** [comment]
@NetanelBasal it is done, after new changes the modal looks like this.

image

**Comment by NetanelBasal** [comment]
Can you please follow the commit guidance and add a breaking change?

**Comment by gethari** [comment]
@NetanelBasal sorry for inconvenience, I think I have added a breaking change. Can you please check now ?

**Comment by NetanelBasal** [comment]
I don't see. Please use npm run commit and follow the questions

**Comment by gethari** [comment]
> I don't see. Please use npm run commit and follow the questions

Thank you for showing me the way `npm run commit` , I was not used to committing like this earlier, good to know that there's a package for handling these kind of things. Nice learning 💡 for me. I think it should be good to go now.

**Comment by gethari** [comment]
Looks like the tests are failing, I will try to fix them

**Comment by gethari** [comment]
@NetanelBasal can you please check now, I have fixed the tests

**Review by netanel-utila — APPROVED** [review]

**Comment by gethari** [comment]
Thanks for the quick action @netanel-utila & @NetanelBasal , could you please publish the `1.4.x` version ? I couldn't able to find it on releases ?

**Comment by NetanelBasal** [comment]
done

**Pull request merged**
